[package]
name = "virtci"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.13"
serde = { version = "1", features = ["derive"] }
serde_yml = "0.0.12"
serde_json = "1.0.149"
russh = { version = "0.56", default-features = false, features = ["aws-lc-rs"] }
russh-sftp = "2.0"
tokio = { version = "1", features = ["rt", "net", "time", "io-util", "macros", "process", "sync", "signal"] }
colored = "3"
tar = "0.4"

[build-dependencies]
cc = "1.2.27"

[[bin]]
name = "virtci"
path = "src/main.rs"